In [1]:
pip install ucimlrepo

Note: you may need to restart the kernel to use updated packages.


In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
cdc_diabetes_health_indicators = fetch_ucirepo(id=891) 
  
# data (as pandas dataframes) 
X = cdc_diabetes_health_indicators.data.features #this is the df
y = cdc_diabetes_health_indicators.data.targets 
  
# metadata 
print(cdc_diabetes_health_indicators.metadata) 
  
# variable information 
print(cdc_diabetes_health_indicators.variables) 



{'uci_id': 891, 'name': 'CDC Diabetes Health Indicators', 'repository_url': 'https://archive.ics.uci.edu/dataset/891/cdc+diabetes+health+indicators', 'data_url': 'https://archive.ics.uci.edu/static/public/891/data.csv', 'abstract': 'The Diabetes Health Indicators Dataset contains healthcare statistics and lifestyle survey information about people in general along with their diagnosis of diabetes. The 35 features consist of some demographics, lab test results, and answers to survey questions for each patient. The target variable for classification is whether a patient has diabetes, is pre-diabetic, or healthy. ', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Tabular', 'Multivariate'], 'num_instances': 253680, 'num_features': 21, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Sex', 'Age', 'Education Level', 'Income'], 'target_col': ['Diabetes_binary'], 'index_col': ['ID'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_

In [3]:
y

Diabetes_binary
0                     0
1                     0
2                     0
3                     0
4                     0
...                 ...
253675                0
253676                1
253677                0
253678                0
253679                1

[253680 rows x 1 columns]

In [5]:
import pandas as pd

df = pd.concat([X, y], axis=1)

df

HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
0            1         1          1   40       1       0   
1            0         0          0   25       1       0   
2            1         1          1   28       0       0   
3            1         0          1   27       0       0   
4            1         1          1   24       0       0   
...        ...       ...        ...  ...     ...     ...   
253675       1         1          1   45       0       0   
253676       1         1          1   18       0       0   
253677       0         0          1   28       0       0   
253678       1         0          1   23       0       0   
253679       1         1          1   25       0       0   

        HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  NoDocbcCost  \
0                          0             0       0        1  ...            0   
1                          0             1       0        0  ...            1   
2                          0             0       1        0  ...            1   
3                          0             1       1        1  ...            0   
4                          0             1       1        1  ...            0   
...                      ...           ...     ...      ...  ...          ...   
253675                     0             0       1        1  ...            0   
253676                     0             0       0        0  ...            0   
253677                     0             1       1        0  ...            0   
253678                     0             0       1        1  ...            0   
253679                     1             1       1        0  ...            0   

        GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  Age  Education  Income  \
0             5        18        15         1    0    9          4       3   
1             3         0         0         0    0    7          6       1   
2             5        30        30         1    0    9          4       8   
3             2         0         0         0    0   11          3       6   
4             2         3         0         0    0   11          5       4   
...         ...       ...       ...       ...  ...  ...        ...     ...   
253675        3         0         5         0    1    5          6       7   
253676        4         0         0         1    0   11          2       4   
253677        1         0         0         0    0    2          5       2   
253678        3         0         0         0    1    7          5       1   
253679        2         0         0         0    0    9          6       2   

        Diabetes_binary  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
...                 ...  
253675                0  
253676                1  
253677                0  
253678                0  
253679                1  

[253680 rows x 22 columns]

In [10]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

In [11]:
#Split data
X = df.drop('Diabetes_binary',axis=1)
y = df['Diabetes_binary']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [32]:
# 1 Logistic Regression
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LR_train_accuracy = model.score(X_train, y_train)

LR_test_accuracy = model.score(X_test, y_test)

# Predict the values
LR_test_y = model.predict(X_test)

LR_mse = mean_squared_error(y_test, LR_test_y)

/Users/vikali/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [28]:
LR_train_accuracy

0.8613563895020848

In [29]:
LR_test_accuracy 

0.8641595711132135

In [30]:
LR_mse

0.1358404288867865

In [67]:
from sklearn.metrics import confusion_matrix
confusion_matrix_LR = confusion_matrix(y_test, LR_test_y)

In [68]:
confusion_matrix_LR

array([[21316,   558],
       [ 2888,   606]])

In [72]:
# 2 the Decision Tree model
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix

tree = DecisionTreeRegressor(random_state=0, max_depth=5)
tree.fit(X_train, y_train)

# MSE on the test set
Tree_test_y = tree.predict(X_test)
Tree_mse = mean_squared_error(y_test, Tree_test_y)


confusion_matrix_tree = confusion_matrix(y_test, y_test_pred)

In [53]:
Tree_mse

0.09937156643031544

In [73]:
confusion_matrix_tree

array([[17628,  4246],
       [ 1483,  2011]])

In [ ]:
pip uninstall scikit-learn


In [81]:
pip install scikit-learn==1.2.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 8.7 MB/s eta 0:00:0000:0100:01m
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.3.0
    Uninstalling scikit-learn-1.3.0:
      Successfully uninstalled scikit-learn-1.3.0
Note: you may need to restart the kernel to use updated packages.


In [ ]:
# 3 KNN 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

model = KNeighborsClassifier()
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

accuracy_score(y_test,y_pred)

In [78]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

model = KNeighborsClassifier()
model.fit(X_train, y_train)

# Predict the values for training and test data
y_train_pred_knn = model.predict(X_train)
y_test_pred_knn = model.predict(X_test)

# Compute accuracy for training set
accuracy_train = accuracy_score(y_train, y_train_pred_knn)

# Compute accuracy for test set
accuracy_test = accuracy_score(y_test, y_test_pred_knn)

# Compute confusion matrix for test set
confusion_matrix_knn = confusion_matrix(y_test, y_test_pred_knn)


AttributeError: 'Flags' object has no attribute 'c_contiguous'

In [60]:
# 4 Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix

classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predict the values for training and test data
y_train_pred = classifier.predict(X_train)
y_test_pred = classifier.predict(X_test)

# Compute accuracy for training set
accuracy_train = accuracy_score(y_train, y_train_pred)

# Compute accuracy for test set
accuracy_test = accuracy_score(y_test, y_test_pred)

# Print the accuracies
print("Training Accuracy:", accuracy_train)
print("Test Accuracy:", accuracy_test)

confusion_matrix = confusion_matrix(y_test, y_test_pred)

Training Accuracy: 0.773406566452924
Test Accuracy: 0.7741643014821823


In [61]:
confusion_matrix

array([[17628,  4246],
       [ 1483,  2011]])

In [ ]:
# 5 neural network 

